### ISSUE TITLE
Adal issue happening which i believe is blocking silent auth

### ISSUE THREAD

**Issue by icatchx22i** [ydogandjiev/taskmeow#31] opened 2020-04-06 20:02 UTC
Hi @ydogandjiev  and thank you for your comment. I was able to install as per the instructions and can log in. What i noticed is that the app receives this error, which basically blocks the silent login feature. I have seen this in the official Complete Node example as well:
From console: 

adal.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined
    at AuthenticationContext.getRequestInfo (adal.min.js:2)
    at AuthenticationContext.handleWindowCallback (adal.min.js:2)
    at silent-end:13

silent-end:13 = ' authContext.handleWindowCallback(window.location.hash);

 Googling the Error itself leads to comments stating ADAL is not being worked on anymore and that one should MSAL and is basically a dead-end. Is MSAL the way to go with MSTeams tabs in 2020? everything about the documentation of MSTeams suggests that it is **not** and ADAL is still the way to go. thanks and apologies if im barking up the wrong tree. Thanks for the demo app :)

_Originally posted by @icatchx22i in https://github.com/ydogandjiev/taskmeow/issues/28#issuecomment-605694864_

**Comment by ydogandjiev** [comment] 2020-04-19 06:46
Hey @icatchx22i, I was able to reproduce this error and spent some time investigating the issue. I believe this is caused by a bug in ADAL.js that has been resolved in the latest version of the library. I made a change (3592ee8cd9a60ff713819c00245b4e246dfabfa7) upgrading ADAL.js from v1.0.15 to v1.0.17 and as far as I can tell the issue has now been resolved and I am no longer seeing the error.

**Closed by ydogandjiev** 2020-04-19 06:46 UTC
